name: Go

env:
  GOPRIVATE: "github.com/carted"

on:
  workflow_call:
    secrets:
      token:
        description: "The GitHub token to use for the workflow."
        required: true
    inputs:
      go-version:
        description: "The Go version to use for the build."
        required: false
        type: string
        default: 1.18
      github-username:
        description: "The GitHub username to use for the build."
        required: false
        type: string
        default: "cartedbot"
jobs:
  build:
    runs-on: [ self-hosted, linux ]
    steps:
      - name: Cleanup
        run: |
          cd ~
          cat .gitconfig
          rm -rf .gitconfig

      - name: Git
        uses: actions/checkout@v3

      - name: Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: GO
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}

      - name: Private GitHub repos
        run: git config --global url."https://${{ inputs.github-username }}:${{ secrets.token }}@github.com/carted".insteadOf "https://github.com/carted"

      - name: Tests
        run: go test -v ./...

      - name: Test the build
        run: go build -v ./...
