name: Linting

env:
  GITHUB_USERNAME: "cartedbot"
  GITHUB_TOKEN: ${{ secrets.CARTEDBOT_GITHUB_TOKEN }}
  GOPRIVATE: "github.com/carted"

#on:
#  push:
#    branches: [ '*', '!main' ]
#  pull_request:
#    branches: [ 'main' ]
#
on:
  workflow_call:
jobs:
  golangci:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
          args: "--out-${NO_FUTURE}format colored-line-number"

          # Optional: golangci-lint command line arguments.
          #          args: --out-format=github-actions

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          skip-cache: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
