name: Linting

env:
  GITHUB_USERNAME: "cartedbot"
  GITHUB_TOKEN: ${{ secrets.CARTEDBOT_GITHUB_TOKEN }}
  GOPRIVATE: "github.com/carted"

on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  golangci:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Get github-workflows
        uses: actions/checkout@v3
        with:
          repository: carted/github-workflows
          path: './.workdir/github-workflows/'
          token: ${{ secrets.token }}
      - name: run
        run: |
          cd .workdir && ls 
          cd github-workflows && ls
          cd linting && ls
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
          args: "--out-${NO_FUTURE}format colored-line-number --config ./.workdir/github-workflows/linting/.golangci.yml"
          only-new-issues: true
          skip-cache: true
