name: Linting

env:
  GOPRIVATE: "github.com/carted"

on:
  workflow_call:
    secrets:
      token:
        description: "The GitHub token to use for the workflow."
        required: true
    inputs:
      go-version:
        description: "The Go version to use for the build."
        required: false
        type: string
        default: 1.18
jobs:
  golangci:
    runs-on: [ self-hosted, linux ]
    steps:
      - name: Cleanup
        run: |
          cd ~
          rm -rf .gitconfig

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}

      - name: Get source
        uses: actions/checkout@v3

      - name: Get github-workflows repository
        uses: actions/checkout@v3
        with:
          repository: carted/github-workflows
          path: './.workdir/github-workflows/'
          token: ${{ secrets.token }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: 1.46.2
          args: "--out-${NO_FUTURE}format colored-line-number --config ./.workdir/github-workflows/linting/.golangci.yml"
          only-new-issues: true
          skip-cache: true
